/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.gray-bg[_ngcontent-%COMP%] {\r\n    opacity: 0.4;\r\n    background-color: black;\r\n    left:0px;\r\n    top:0px;\r\n    width:100%;\r\n    height:100%;\r\n    position: fixed;\r\n}\r\n\r\n.flight-history[_ngcontent-%COMP%] {\r\n    left:0px;\r\n    top:0px;\r\n    width:100%;\r\n    height:100%;\r\n    position: fixed;\r\n}\r\n\r\n.flight-history-inside[_ngcontent-%COMP%] {\r\n    background-color: white;\r\n    margin: 100px auto;\r\n    width: 400px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFuZnJlZC9Eb2N1bWVudHMvS25vd0hvdy9uZ3J4L3RyYWluZXJfc3RhcnRlci9zcmMvYXBwL2Jhc2tldC9iYXNrZXQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NYW5mcmVkL0RvY3VtZW50cy9Lbm93SG93L25ncngvdHJhaW5lcl9zdGFydGVyL3NyYy9hcHAvYmFza2V0L2Jhc2tldC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
