/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['input.ng-invalid[_ngcontent-%COMP%] {\r\n  border-left: 5px solid chocolate;\r\n}\r\n\r\ninput.ng-valid[_ngcontent-%COMP%] {\r\n  border-left: 5px solid cadetblue;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFuZnJlZC9Eb2N1bWVudHMvS25vd0hvdy9uZ3J4L3RyYWluZXJfc3RhcnRlci9zcmMvYXBwL2ZsaWdodC1ib29raW5nL2ZsaWdodC1zZWFyY2gvZmxpZ2h0LXNlYXJjaC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL01hbmZyZWQvRG9jdW1lbnRzL0tub3dIb3cvbmdyeC90cmFpbmVyX3N0YXJ0ZXIvc3JjL2FwcC9mbGlnaHQtYm9va2luZy9mbGlnaHQtc2VhcmNoL2ZsaWdodC1zZWFyY2guY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
